In [2]:
import numpy as np

# Vector

In [31]:
a  = np.array( [1.0, 2.0, 3.0])
print(a)
print(a.shape)
print(a.size)

[1. 2. 3.]
(3,)
3


# Vector norm

In [32]:
from numpy.linalg import norm
# define vector
a = np.array([1, 2, -3,-4])
print(a)
# calculate norm

#sum of absolute values
l1 = norm(a, 1)
# the square root of the sum of the squared vector values.
l2 = norm(a,2)

l3 =norm(a,3)
print(l1)
print(l2)
print(l3)

[ 1  2 -3 -4]
10.0
5.477225575051661


In [40]:
a = np.array([1, 2, 3])
print(a)

# define second vector
b = np.array([1, 2, 3])
print(b)
print('\n')




# multiply vectors
c = a.dot(b)
print(c)
#new vector x
x = np.array([1, 4, 3])

d=np.cross(a,x)

print(d)

[1 2 3]
[1 2 3]


14
[-6  0  2]


# Matrix

In [12]:
A = np.array([[1, 2, 3], 
              [4, 5, 6]])
print(A)


[[1 2 3]
 [4 5 6]]


In [19]:
A = np.array([
[1, 2, 3],
[4, 5, 6]])
print(A)
# define second matrix
B = np.array([
[1, 4, 3],
[4, 5, 6]])

print(B)
print('\n')

# add matrices
C = A + B
print(C)

print('\n')


# subtract  matrices
C = A - B
print(C)



[[1 2 3]
 [4 5 6]]
[[1 4 3]
 [4 5 6]]


[[ 2  6  6]
 [ 8 10 12]]


[[ 0 -2  0]
 [ 0  0  0]]


# Element wise

In [39]:
print(A * B)
print('\n')
type(A * B)
print(np.multiply(A,B))
print(np.multiply(A,B))


[[ 15  30  45]
 [ 60  75  90]
 [105 120 135]]


[[ 15  30  45]
 [ 60  75  90]
 [105 120 135]]
[[ 15  30  45]
 [ 60  75  90]
 [105 120 135]]


In [23]:
A = np.array([
[1, 2],
[3, 4],
[5, 6]])
print(A)

# define second matrix
B = np.array([
[1, 2],
[3, 4]])
print(B)

# multiply matrices
C = A.dot(B)
print(C)
# multiply matrices with @ operator
D = A @ B
print(D)

[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]]
[[ 7 10]
 [15 22]
 [23 34]]
[[ 7 10]
 [15 22]
 [23 34]]


# Matrix-Vector Multiplication

In [26]:
A = np.array([
[1, 2],
[3, 4],
[5, 6]])
print(A)
print('\n')

# define vector
B = np.array([0.5, 0.5])
print(B)
print('\n')

# multiply
C = A.dot(B)
print(C)


[[1 2]
 [3 4]
 [5 6]]


[0.5 0.5]


[1.5 3.5 5.5]


In [27]:
from numpy import array
# define matrix
A = np.array([
[1, 2],
[3, 4],
[5, 6]])
print(A)
print('\n')

# calculate transpose
C = A.T
print(C)

[[1 2]
 [3 4]
 [5 6]]


[[1 3 5]
 [2 4 6]]


In [42]:
from numpy.linalg import inv
from numpy.linalg import det

from numpy import linalg 
A = np.array([
[1.0, 2.0],
[3.0, 4.0]])
print(A)
print('\n')

# invert matrix
B =linalg.inv(A)
print(B)


print('\n')

# multiply A and B
I = A.dot(B)
print(I)
print('\n')

#printing det
print(det(A))

[[1. 2.]
 [3. 4.]]


[[-2.   1. ]
 [ 1.5 -0.5]]


[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


-2.0000000000000004


In [30]:
from numpy import trace



# define matrix
A = np.array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
print(A)
print('\n')

# calculate trace
B = trace(A)
print(B)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


15


# Differential Method

## one variable 

In [ ]:
import sympy as sp
x = sp.Symbol('x')
fx =  x**2020 + 3*x*x*x -1


In [ ]:
sp.diff(fx,x)

In [ ]:
x = sp.Symbol('x')
gx = x/(x+1)
sp.diff(gx,x)

In [ ]:
sp.simplify(sp.diff(gx,x))

In [ ]:
x= sp.simplify('x')
fx = sp.exp(x)/x
sp.diff(fx,x)

In [ ]:
sp.simplify(sp.diff(fx,x))

In [ ]:
x = sp.Symbol('x')
gx = 3 *  sp.log(x,2) - x * sp.log(x)
sp.simplify(sp.diff(gx,x))

In [ ]:
x = sp.Symbol('x')
fx = (x**2+2)**3
sp.diff(fx,x)

## two variables

In [ ]:
x, y, z = sp.symbols('x y z')
fx =  x**2020 + 3*y*y -6*z*z  
fx

In [ ]:
# par rapport à x
sp.diff(fx,x)

In [ ]:
# par rapport à y
sp.diff(fx,y)

In [ ]:
# par rapport à z
sp.diff(fx,z)